services:
  db_ab:
    image: mysql:latest
    restart: always
    container_name: db_ab_c
    env_file:
      - .env
    ports:
    - '3306:3306'
    volumes:
    - ../:/appdata
    - ${PWD}/aestheticblasphemy.sql:/docker-entrypoint-initdb.d/aestheticblasphemy.sql
    #network_mode: "host"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: ab_c
    volumes:
    - .:/app
    - ../static:/static
    - ../media:/media
    ports:
    - "8000:8000"
    #network_mode: "host"
    depends_on:
      - db_ab
