# Generated by Django 3.1 on 2020-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'IT-Professional'), (2, 'Telecom-Engineer'), (3, 'Achedmic'), (4, 'Algorithm'), (5, 'Analog'), (6, 'Digital')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signin_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
