# Generated by Django 3.1 on 2020-08-28 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pl_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pl_messages.messages'),
        ),
        migrations.AlterField(
            model_name='participantnotifications',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_participant', to=settings.AUTH_USER_MODEL, verbose_name='Notification Participant'),
        ),
        migrations.AlterField(
            model_name='participantthreads',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_participant', to=settings.AUTH_USER_MODEL, verbose_name='Thread Participant'),
        ),
        migrations.AlterField(
            model_name='participantthreads',
            name='threads',
            field=models.ManyToManyField(related_name='participant_threads', to='pl_messages.Thread', verbose_name='Participant Threads'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_message_in_thread', to='pl_messages.messages', verbose_name='Last Message'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='messages',
            field=models.ManyToManyField(related_name='thread_messages', to='pl_messages.Messages', verbose_name='Thread Messages'),
        ),
    ]
