# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(verbose_name='object ID')),
                ('body', models.TextField()),
                ('paragraph', models.PositiveIntegerField()),
                ('privacy', models.PositiveSmallIntegerField(choices=[(0, b'public'), (1, b'author'), (2, b'group'), (3, b'private')], default=3)),
                ('privacy_override', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL, verbose_name='Annotation author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_annotations', to='contenttypes.ContentType', verbose_name='Content Type')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationShareMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_flag', models.BooleanField(default=False)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotations.Annotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_shared_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='shared_with',
            field=models.ManyToManyField(blank=True, through='annotations.AnnotationShareMap', to=settings.AUTH_USER_MODEL),
        ),
    ]
