# Generated by Django 3.1 on 2020-08-28 15:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogparent',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogging.blogcontenttype'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='publication_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='published on'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='published_flag',
            field=models.BooleanField(default=0, verbose_name='is published?'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='section',
            field=models.ForeignKey(limit_choices_to={'children': None}, on_delete=django.db.models.deletion.CASCADE, to='blogging.blogparent'),
        ),
        migrations.AlterField(
            model_name='blogcontenttype',
            name='is_leaf',
            field=models.BooleanField(default=0, verbose_name='Is leaf node?'),
        ),
        migrations.AlterField(
            model_name='blogparent',
            name='content_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogging.blogcontenttype'),
        ),
        migrations.AlterField(
            model_name='blogparent',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='blogparent',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='blogparent',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blogging.blogparent'),
        ),
        migrations.AlterField(
            model_name='blogparent',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
