# Generated by Django 3.1 on 2020-08-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_auto_20200828_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.blogparent'),
        ),
    ]
